lmao:
	cd /Users/mraoaakash/Documents/TNBC/histoImgSplit
	python3 /Users/mraoaakash/Documents/TNBC/histoImgSplit/patchGenerator/keys.py
	python3 /Users/mraoaakash/Documents/TNBC/histoImgSplit/patchGenerator/splitter.py