lmao:
	cd /Users/mraoaakash/Documents/research/research-tnbc/histoImgSplit
	python3 /Users/mraoaakash/Documents/research/research-tnbc/histoImgSplit/patchGenerator/keys.py
	python3 /Users/mraoaakash/Documents/research/research-tnbc/histoImgSplit/patchGenerator/splitter.py